Repository hyperledger/quilt, pull requests merged in 2019-10, with the labels that each got.

#316 Df/fix poms for release
  README.md
  btp-core/pom.xml
  codecs-parent/codecs-btp/pom.xml
  codecs-parent/codecs-framework/pom.xml
  codecs-parent/codecs-ildcp/pom.xml
  codecs-parent/codecs-ilp/pom.xml
  codecs-parent/codecs-stream/pom.xml
  codecs-parent/pom.xml
  examples-parent/README.md
  examples-parent/pom.xml
  examples-parent/send-money/README.md
  examples-parent/send-money/pom.xml
  examples-parent/send-money/src/main/java/org/interledger/examples/SendMoneyExample.java
  ildcp-core/pom.xml
  ilp-core/pom.xml
  jackson-datatypes/pom.xml
  link-parent/link-core/pom.xml
  link-parent/link-ilp-over-http/pom.xml
  link-parent/pom.xml
  pom.xml
  spsp-parent/pom.xml
  spsp-parent/spsp-client/pom.xml
  spsp-parent/spsp-core/pom.xml
  stream-parent/pom.xml
  stream-parent/stream-client/pom.xml
  stream-parent/stream-core/pom.xml
  stream-parent/stream-receiver/pom.xml
  stream-parent/stream-receiver/src/test/java/org/interledger/stream/receiver/SenderReceiverTest.java
Labels: v1.0

#320 Df/fixes 201
  btp-core/src/main/java/org/interledger/btp/BtpTransfer.java
  btp-core/src/test/java/org/interledger/btp/BtpTransferTest.java
  codecs-parent/codecs-btp/src/test/java/org/interledger/codecs/btp/AsnBtpTransferDataCodecTest.java
  codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/codecs/AsnUint64Codec.java
  codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/codecs/AsnUint64CodecUL.java
  codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/framework/CodecContextFactory.java
  codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/serializers/oer/AsnSequenceOfSequenceOerSerializer.java
  codecs-parent/codecs-framework/src/test/java/org/interledger/encoding/MyCustomObject.java
  codecs-parent/codecs-framework/src/test/java/org/interledger/encoding/asn/framework/EncodingTests.java
  codecs-parent/codecs-framework/src/test/java/org/interledger/encoding/asn/serializers/oer/AbstractSerializerTest.java
  codecs-parent/codecs-framework/src/test/java/org/interledger/encoding/asn/serializers/oer/BigIntegerOerSerializerTest.java
  codecs-parent/codecs-framework/src/test/java/org/interledger/encoding/asn/serializers/oer/UnsignedLongOerSerializerTest.java
  codecs-parent/codecs-ildcp/pom.xml
  codecs-parent/codecs-ildcp/src/test/java/org/interledger/codecs/ildcp/AsnIldcpRequestPacketDataCodecTest.java
  codecs-parent/codecs-ilp/pom.xml
  codecs-parent/codecs-ilp/src/test/java/org/interledger/codecs/ilp/InterledgerPreparePacketOerSerializerTests.java
  codecs-parent/codecs-stream/src/main/java/org/interledger/codecs/stream/AsnAmountTooLargeDataCodec.java
  codecs-parent/codecs-stream/src/main/java/org/interledger/codecs/stream/frame/AsnConnectionDataBlockedFrameDataCodec.java
  codecs-parent/codecs-stream/src/main/java/org/interledger/codecs/stream/frame/AsnConnectionDataMaxFrameDataCodec.java
  codecs-parent/codecs-stream/src/main/java/org/interledger/codecs/stream/frame/AsnConnectionMaxStreamIdFrameDataCodec.java
  codecs-parent/codecs-stream/src/main/java/org/interledger/codecs/stream/frame/AsnConnectionStreamIdBlockedFrameDataCodec.java
  codecs-parent/codecs-stream/src/main/java/org/interledger/codecs/stream/frame/AsnStreamDataBlockedFrameDataCodec.java
  codecs-parent/codecs-stream/src/main/java/org/interledger/codecs/stream/frame/AsnStreamMoneyBlockedFrameDataCodec.java
  codecs-parent/codecs-stream/src/main/java/org/interledger/codecs/stream/frame/AsnStreamMoneyFrameDataCodec.java
  codecs-parent/codecs-stream/src/main/java/org/interledger/codecs/stream/frame/AsnStreamMoneyMaxFrameDataCodec.java
  codecs-parent/codecs-stream/src/test/java/org/interledger/codecs/stream/frame/FrameCodecPerfTest.java
  ildcp-core/src/main/java/org/interledger/ildcp/IldcpRequest.java
  ildcp-core/src/main/java/org/interledger/ildcp/IldcpRequestPacket.java
  ildcp-core/src/test/java/org/interledger/ildcp/IldcpRequestPacketTest.java
  ildcp-core/src/test/java/org/interledger/ildcp/IldcpRequestTest.java
  ilp-core/pom.xml
  ilp-core/src/main/java/org/interledger/core/InterledgerPreparePacket.java
  ilp-core/src/test/java/org/interledger/core/InterledgerPreparePacketTest.java
  link-parent/link-core/src/test/java/org/interledger/link/LoopbackLinkTest.java
  link-parent/link-core/src/test/java/org/interledger/link/PacketRejectorTest.java
  link-parent/link-core/src/test/java/org/interledger/link/PingLoopbackLinkTest.java
  pom.xml
  spsp-parent/spsp-client/src/main/java/org/interledger/spsp/client/rust/Account.java
  spsp-parent/spsp-client/src/test/java/org/interledger/spsp/client/rust/InterledgerRustNodeClientTest.java
  stream-parent/stream-client/src/main/java/org/interledger/stream/sender/AimdCongestionController.java
  stream-parent/stream-client/src/main/java/org/interledger/stream/sender/SimpleStreamSender.java
  stream-parent/stream-client/src/main/java/org/interledger/stream/sender/StreamConnectionManager.java
  stream-parent/stream-receiver/src/main/java/org/interledger/stream/receiver/StatelessStreamReceiver.java
  stream-parent/stream-receiver/src/main/java/org/interledger/stream/receiver/StreamReceiver.java
  stream-parent/stream-receiver/src/test/java/org/interledger/stream/receiver/SenderReceiverTest.java
  stream-parent/stream-receiver/src/test/java/org/interledger/stream/receiver/StatelessStreamReceiverTest.java
  stream-parent/stream-receiver/src/test/java/org/interledger/stream/receiver/testutils/SimulatedIlpv4Network.java
Labels: ilp-core, v1.0

#327 Nh/payment tracker modes
  examples-parent/send-money/src/main/java/org/interledger/examples/SendMoneyExample.java
  stream-parent/stream-client/src/main/java/org/interledger/stream/sender/AimdCongestionController.java
  stream-parent/stream-client/src/main/java/org/interledger/stream/sender/FixedReceiverAmountPaymentTracker.java
  stream-parent/stream-client/src/main/java/org/interledger/stream/sender/FixedSenderAmountPaymentTracker.java
  stream-parent/stream-client/src/main/java/org/interledger/stream/sender/SimpleStreamSender.java
  stream-parent/stream-client/src/main/java/org/interledger/stream/sender/StreamSender.java
  stream-parent/stream-client/src/test/java/org/interledger/stream/sender/FixedReceiverAmountPaymentTrackerTest.java
  stream-parent/stream-client/src/test/java/org/interledger/stream/sender/FixedSenderAmountPaymentTrackerTest.java
  stream-parent/stream-client/src/test/java/org/interledger/stream/sender/HalfsiesExchangeRateCalculator.java
  stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SendMoneyAggregatorTest.java
  stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SimpleStreamSenderIT.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/Denominations.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/FluentCompareTo.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/PaymentTracker.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/PrepareAmounts.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/ReceiverAmountPaymentTracker.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/SendMoneyRequest.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/SendMoneyResult.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/SenderAmountMode.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/SenderAmountPaymentTracker.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/StreamConnection.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/StreamPacket.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/StreamUtils.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/calculators/ExchangeRateCalculator.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/calculators/NoOpExchangeRateCalculator.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/crypto/JavaxStreamEncryptionService.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/DenominationsTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/FluentCompareToTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/PrepareAmountsTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/SendMoneyResultTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/calculators/ExchangeRateCalculatorTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/calculators/NoOpExchangeRateCalculatorTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/crypto/JavaxStreamEncryptionServiceTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/crypto/SharedSecretTest.java
  stream-parent/stream-receiver/src/main/java/org/interledger/stream/receiver/StatelessStreamReceiver.java
  stream-parent/stream-receiver/src/test/java/org/interledger/stream/receiver/SenderReceiverTest.java
  stream-parent/stream-receiver/src/test/java/org/interledger/stream/receiver/testutils/SimulatedIlpv4Network.java
Labels: STREAM, v1.0

#332 Update README.md for v1.0 release
  README.md
Labels: v1.0

#333 Df/prepare for release
  README.md
  pom.xml
Labels: v1.0

#339 Update README.md
  README.md
  ilp-core/README.md
Labels: v1.0

#342 Fixes #341 (Make Quilt work on Android)
  .circleci/config.yml
  ilp-core/pom.xml
  link-parent/link-ilp-over-http/src/main/java/org/interledger/link/http/auth/JwtHs256BearerTokenSupplier.java
  link-parent/link-ilp-over-http/src/test/java/org/interledger/link/http/auth/JwtHs256BearerTokenSupplierTest.java
  pom.xml
Labels: android, v1.0

#353 fixes for JDK9+
  btp-core/src/main/java/org/interledger/btp/BtpError.java
  btp-core/src/main/java/org/interledger/btp/BtpResponsePacket.java
  btp-core/src/main/java/org/interledger/btp/BtpRuntimeException.java
  btp-core/src/test/java/org/interledger/btp/BtpErrorTest.java
  btp-core/src/test/java/org/interledger/btp/BtpResponsePacketTest.java
  codecs-parent/codecs-btp/src/test/java/org/interledger/codecs/btp/AsnBtpErrorDataCodecTest.java
  codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/codecs/AsnObjectCodecBase.java
  codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/framework/AsnObjectCodec.java
  codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/framework/AsnObjectCodecRegistry.java
  codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/framework/AsnObjectCodecSupplier.java
  codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/framework/AsnObjectSerializationContext.java
  codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/framework/CodecContext.java
  codecs-parent/codecs-framework/src/test/java/org/interledger/encoding/asn/serializers/oer/AbstractSerializerTest.java
  codecs-parent/codecs-ilp/src/test/java/org/interledger/codecs/ilp/InterledgerPreparePacketOerSerializerTests.java
  ildcp-core/src/main/java/org/interledger/ildcp/IldcpRequest.java
  ildcp-core/src/main/java/org/interledger/ildcp/IldcpRequestPacket.java
  ildcp-core/src/main/java/org/interledger/ildcp/IldcpResponsePacketMapper.java
  ildcp-core/src/test/java/org/interledger/ildcp/IldcpRequestTest.java
  ilp-core/src/main/java/org/interledger/core/DateUtils.java
  ilp-core/src/main/java/org/interledger/core/InterledgerResponsePacket.java
  ilp-core/src/test/java/org/interledger/core/DateUtilsTest.java
  ilp-core/src/test/java/org/interledger/core/InterledgerPreparePacketTest.java
  link-parent/link-core/src/main/java/org/interledger/link/AbstractLink.java
  link-parent/link-core/src/main/java/org/interledger/link/AbstractStatefulLink.java
  link-parent/link-core/src/main/java/org/interledger/link/Link.java
  link-parent/link-core/src/main/java/org/interledger/link/LinkFactory.java
  link-parent/link-core/src/test/java/org/interledger/link/LoopbackLinkTest.java
  link-parent/link-core/src/test/java/org/interledger/link/PacketRejectorTest.java
  link-parent/link-core/src/test/java/org/interledger/link/PingLoopbackLinkTest.java
  link-parent/link-ilp-over-http/src/main/java/org/interledger/link/http/IlpOverHttpLink.java
  link-parent/link-ilp-over-http/src/main/java/org/interledger/link/http/auth/JwtHs256BearerTokenSupplier.java
  stream-parent/stream-client/src/main/java/org/interledger/stream/sender/SimpleStreamSender.java
  stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SendMoneyAggregatorTest.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/StreamConnection.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/StreamConnectionTest.java
Labels: v1.0

#349 Fixes #345 Builds the project on available JDK images in CircleCI config
  .circleci/config.yml
  pom.xml
  stream-parent/stream-client/src/test/java/org/interledger/stream/sender/SendMoneyAggregatorTest.java
Labels: v1.0

#354 Df/improve stream test vectors
  codecs-parent/codecs-framework/pom.xml
  codecs-parent/codecs-framework/src/main/java/org/interledger/encoding/asn/codecs/AsnUintCodecUL.java
  codecs-parent/codecs-framework/src/test/java/org/interledger/encoding/asn/codecs/AsnUintCodecULTest.java
  codecs-parent/codecs-stream/pom.xml
  codecs-parent/codecs-stream/src/main/java/org/interledger/codecs/stream/frame/AsnConnectionCloseFrameDataCodec.java
  codecs-parent/codecs-stream/src/main/java/org/interledger/codecs/stream/frame/AsnStreamCloseFrameDataCodec.java
  codecs-parent/codecs-stream/src/main/java/org/interledger/codecs/stream/frame/AsnStreamMoneyBlockedFrameDataCodec.java
  codecs-parent/codecs-stream/src/main/java/org/interledger/codecs/stream/frame/AsnStreamMoneyMaxFrameDataCodec.java
  codecs-parent/codecs-stream/src/test/java/org/interledger/codecs/stream/StreamPacketFixturesTest.java
  codecs-parent/codecs-stream/src/test/java/org/interledger/codecs/stream/frame/AsnConnectionCloseFrameCodecTest.java
  codecs-parent/codecs-stream/src/test/java/org/interledger/codecs/stream/frame/AsnStreamCloseFrameCodecTest.java
  codecs-parent/codecs-stream/src/test/java/org/interledger/codecs/stream/frame/AsnStreamMoneyMaxFrameCodecTest.java
  codecs-parent/codecs-stream/src/test/java/org/interledger/codecs/stream/frame/ValidStreamFrameVectorsTest.java
  codecs-parent/codecs-stream/src/test/java/org/interledger/codecs/stream/frame/helpers/StreamFrameFixture.java
  codecs-parent/codecs-stream/src/test/java/org/interledger/codecs/stream/frame/helpers/StreamPacketFixture.java
  codecs-parent/codecs-stream/src/test/java/org/interledger/codecs/stream/frame/helpers/StreamTestFixture.java
  codecs-parent/codecs-stream/src/test/resources/StreamPacketFixtures.json
  codecs-parent/codecs-stream/src/test/resources/ValidStreamFrameVectorsTest.json
  stream-parent/stream-core/src/main/java/org/interledger/stream/frames/ErrorCode.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/frames/ErrorCodeConstants.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/frames/ErrorCodes.java
  stream-parent/stream-core/src/main/java/org/interledger/stream/frames/StreamCloseFrame.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/frames/ErrorCodeTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/frames/ErrorCodesTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/frames/StreamCloseFrameTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/frames/StreamFrameTypeTest.java
  stream-parent/stream-receiver/src/main/java/org/interledger/stream/receiver/StatelessStreamReceiver.java
Labels: stream, v1.0

#358 Fix codacy badge
  README.md
Labels: documentation

#361 Fix LGTM Badge
  README.md
Labels: documentation

#363 Add link Jackson serializers and Fix #362
  ilp-core/src/main/java/org/interledger/core/InterledgerAddress.java
  ilp-core/src/main/java/org/interledger/core/InterledgerAddressPrefix.java
  ilp-core/src/test/java/org/interledger/core/AllocationSchemeTest.java
  ilp-core/src/test/java/org/interledger/core/InterledgerAddressPrefixTest.java
  ilp-core/src/test/java/org/interledger/core/InterledgerAddressSchemeTest.java
  ilp-core/src/test/java/org/interledger/core/InterledgerAddressTest.java
  jackson-datatypes/pom.xml
  jackson-datatypes/src/main/java/org/interledger/quilt/jackson/link/LinkIdDeserializer.java
  jackson-datatypes/src/main/java/org/interledger/quilt/jackson/link/LinkIdModule.java
  jackson-datatypes/src/main/java/org/interledger/quilt/jackson/link/LinkIdSerializer.java
  jackson-datatypes/src/main/java/org/interledger/quilt/jackson/link/LinkTypeDeserializer.java
  jackson-datatypes/src/main/java/org/interledger/quilt/jackson/link/LinkTypeModule.java
  jackson-datatypes/src/main/java/org/interledger/quilt/jackson/link/LinkTypeSerializer.java
  jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkIdContainer.java
  jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkIdDeserializerTest.java
  jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkIdSerializerTest.java
  jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkModuleTest.java
  jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkTypeContainer.java
  jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkTypeIdDeserializerTest.java
  jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkTypeModuleTest.java
  jackson-datatypes/src/test/java/org/interledger/quilt/jackson/link/LinkTypeSerializerTest.java
Labels: bug, ilp-core, test coverage, v1.0

#359 Add CI Build for Java 14 and updates tests to not use spy
  .circleci/config.yml
  ildcp-core/src/test/java/org/interledger/ildcp/IldcpRequestPacketTest.java
  ildcp-core/src/test/java/org/interledger/ildcp/IldcpRequestTest.java
  ildcp-core/src/test/java/org/interledger/ildcp/IldcpResponsePacketTest.java
  link-parent/link-core/src/test/java/org/interledger/link/LinkTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/StreamPacketTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/calculators/ExchangeRateCalculatorTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/frames/StreamCloseFrameTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/frames/StreamDataFrameTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/frames/StreamFrameTypeTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/frames/StreamMoneyBlockedFrameTest.java
  stream-parent/stream-core/src/test/java/org/interledger/stream/frames/StreamMoneyMaxFrameTest.java
Labels: test coverage, v1.0

#364 DCO Attestation for prior commits
  README.md
Labels: v1.0
