Repository hyperledger/quilt, pull requests merged in 2019-08, with the labels that each got.

#210 Fixes #205 Remove dev-ops module having maven script utils and unused SecureRandomProvider
  README.md
  checkstyle.xml
  dev-ops/pom.xml
  dev-ops/src/main/java/org/interledger/mocks/DeterministicSecureRandomAlgorithm.java
  dev-ops/src/main/java/org/interledger/mocks/DeterministicSecureRandomProvider.java
  dev-ops/src/main/kotlin/org/interledger/dev-ops/Build.kt
  dev-ops/src/main/resources/org/interledger/dev-ops/checkstyle.xml
  dev-ops/util/README.md
  dev-ops/util/full_local_install_mvn_package.sh
  dev-ops/util/quick_local_install_mvn_package.sh
  dev-ops/util/show_mvn_dependency_tree.sh
  dev-ops/util/unit_tests.sh
  pom.xml
Labels: ilp-core, v1.0

#226 Df/224 fix checkstyle
  pom.xml
Labels: bug, dependencies

#225 Fixes #202
  btp-core/src/main/java/org/interledger/btp/BtpPacketMapper.java
  btp-core/src/main/java/org/interledger/btp/BtpResponsePacket.java
  btp-core/src/test/java/org/interledger/btp/BtpResponsePacketTest.java
  ildcp-core/src/test/java/org/interledger/ildcp/InterledgerResponsePacketMapperTest.java
  ilp-core/src/main/java/org/interledger/core/InterledgerResponsePacket.java
  ilp-core/src/main/java/org/interledger/core/InterledgerResponsePacketHandler.java
  ilp-core/src/main/java/org/interledger/core/InterledgerResponsePacketMapper.java
  ilp-core/src/test/java/org/interledger/core/InterledgerResponsePacketHandlerTest.java
  ilp-core/src/test/java/org/interledger/core/InterledgerResponsePacketMapperTest.java
  ilp-core/src/test/java/org/interledger/core/InterledgerResponsePacketTest.java
  pom.xml
Labels: enhancement, ilp-core, v1.0
