Repository hyperledger/quilt, pull requests merged in 2020-01, with the labels that each got.

#412 Imported the ILP_OPERATOR_ADDRESS_VALUE variable
  link-parent/link-ilp-over-http/src/main/java/org/interledger/link/http/IlpOverHttpLink.java
Labels: good first issue, v1.0

#411 Make STREAM_SERVER_SECRET_GENERATOR configurable (Fixes #374)
  stream-parent/stream-receiver/src/main/java/org/interledger/stream/receiver/SpspStreamConnectionGenerator.java
  stream-parent/stream-receiver/src/test/java/org/interledger/stream/receiver/SpspStreamStreamConnectionGeneratorTest.java
Labels: V1.1

#426 Introduce Local SPSP Stream Receiver Link
  README.md
  examples-parent/ilp-emitters/pom.xml
  examples-parent/ilp-emitters/src/main/java/org/interledger/examples/packets/IlpPacketEmitter.java
  link-parent/link-stateless-spsp-receiver/pom.xml
  link-parent/link-stateless-spsp-receiver/src/main/java/org/interledger/link/spsp/StatelessSpspReceiverLink.java
  link-parent/link-stateless-spsp-receiver/src/main/java/org/interledger/link/spsp/StatelessSpspReceiverLinkFactory.java
  link-parent/link-stateless-spsp-receiver/src/main/java/org/interledger/link/spsp/StatelessSpspReceiverLinkSettings.java
  link-parent/link-stateless-spsp-receiver/src/test/java/org/interledger/link/spsp/StatelessSpspReceiverLinkFactoryTest.java
  link-parent/link-stateless-spsp-receiver/src/test/java/org/interledger/link/spsp/StatelessSpspReceiverLinkTest.java
  link-parent/pom.xml
  quilt-bom/pom.xml
Labels: enhancement, stream
